# physics/configs/gen_config.yaml
cif_path: "data/ymno3_unpolar.cif"
output_dir: "outputs/stem_domain"

# Supercell choices used across scripts
supercell_configs:
  - [1, 14, 4]
  - [1, 10, 4]
  - [1, 9, 4]
  - [1, 8, 3]
  - [1, 7, 4]
  - [1, 6, 4]

# Polarization/displacement grids
delta_z:
  t2t: null  #[0.350, 0.50, 0.65] 
  tdw: null #[-0.013, 0.008, 0.013]
  typec: [-0.009, -0.014, 0.014]
  typed: null  #[-0.009, -0.014, 0.014]
  updn: [0.014, 0.018, 0.022]

# Augmentation sweep for dataset synthesis
num_aug: 3
noise_levels: [0.01, 0.05, 0.07]
gamma_values: [0.5, 0.8, 1.0]

# Optional: presets for “single image demo”
single_image:
  supercell_index: 3     # selects [1, 8, 3]
  delta_z_typec: 0.009
  noise: 0.050
  gamma: 0.8

# Optional: parameters for custom stepped TDW (if used in generate_single_image.py)
typeB_tdw:
  y_tol: 0.05
  step_direction: -1